import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = process.cwd();
const STORIES_DIR = join(ROOT, 'behavioral', 'stories');
const README = join(ROOT, 'behavioral', 'README.md');
const START = '<!-- MATRIX:START -->';
const END = '<!-- MATRIX:END -->';
const MIN_COVERAGE = 2;

// The 16 Amazon Leadership Principles, in matrix-column order (codes per README legend).
const LP_CODES = [
  'CO', 'OW', 'IS', 'RA', 'LC', 'HD', 'HS', 'TB',
  'BA', 'FR', 'ET', 'DD', 'BB', 'DR', 'EB', 'BR',
] as const;

// The 6 themes, with short column headers. `match` substrings normalize loose frontmatter prose.
const THEMES = [
  { code: 'conflict', head: 'Cf', match: ['conflict'] },
  { code: 'failure', head: 'Fl', match: ['fail'] },
  { code: 'deadline', head: 'Dl', match: ['deadline'] },
  { code: 'ambiguity', head: 'Am', match: ['ambig'] },
  { code: 'influence', head: 'If', match: ['influence'] },
  { code: 'technical', head: 'Tc', match: ['tech'] },
] as const;

interface Story {
  label: string;
  principles: Set<string>;
  themes: Set<string>;
}

/** Extract the YAML frontmatter block (between the first pair of `---` fences). */
function frontmatter(content: string): string {
  const m = content.match(/^---\n([\s\S]*?)\n---/);
  return m ? m[1] : '';
}

/** Parse an inline-array frontmatter field, e.g. `principles: [OW, DD, BA]`. */
function listField(fm: string, key: string): string[] {
  const m = fm.match(new RegExp(`^${key}:\\s*\\[(.*)\\]`, 'm'));
  if (!m) return [];
  return m[1]
    .split(',')
    .map((s) => s.trim().replace(/^['"]|['"]$/g, ''))
    .filter(Boolean);
}

function titleField(fm: string, fallback: string): string {
  const m = fm.match(/^title:\s*(.+)$/m);
  const t = m ? m[1].trim() : fallback;
  // Ignore the unfilled template placeholder.
  return t && !t.startsWith('<') ? t : fallback;
}

function normalizePrinciple(raw: string): string | null {
  const c = raw.trim().toUpperCase();
  return (LP_CODES as readonly string[]).includes(c) ? c : null;
}

function normalizeTheme(raw: string): string | null {
  const s = raw.trim().toLowerCase();
  for (const t of THEMES) {
    if (t.match.some((frag) => s.includes(frag))) return t.code;
  }
  return null;
}

function truncate(s: string, n: number): string {
  return s.length <= n ? s : s.slice(0, n - 1) + '…';
}

function readStories(): Story[] {
  if (!existsSync(STORIES_DIR)) return [];
  const files = readdirSync(STORIES_DIR)
    .filter((f) => f.endsWith('.md') && !f.startsWith('_'))
    .sort();

  return files.map((f) => {
    const content = readFileSync(join(STORIES_DIR, f), 'utf8');
    const fm = frontmatter(content);
    const slug = f.replace(/\.md$/, '');
    const principles = new Set(
      listField(fm, 'principles').map(normalizePrinciple).filter((x): x is string => x !== null),
    );
    const themes = new Set(
      listField(fm, 'themes').map(normalizeTheme).filter((x): x is string => x !== null),
    );
    return { label: truncate(titleField(fm, slug), 24), principles, themes };
  });
}

function buildBlock(stories: Story[]): { block: string; underCovered: string[] } {
  const lpHeads = LP_CODES as readonly string[];
  const themeHeads = THEMES.map((t) => t.head);
  const allHeads = [...lpHeads, ...themeHeads];

  const has = (s: Story, col: string): boolean =>
    s.principles.has(col) || THEMES.some((t) => t.head === col && s.themes.has(t.code));

  const header = `| Story | ${allHeads.join(' | ')} |`;
  const sep = `|${'---|'.repeat(allHeads.length + 1)}`;
  const rows = stories.map((s) => {
    const cells = allHeads.map((col) => (has(s, col) ? '✓' : ''));
    return `| ${s.label} | ${cells.join(' | ')} |`;
  });

  // Per-column coverage counts.
  const counts = allHeads.map((col) => stories.filter((s) => has(s, col)).length);
  const totalRow = `| **Coverage** | ${counts.map((c) => `**${c}**`).join(' | ')} |`;

  const underCovered = allHeads.filter((_, i) => counts[i] < MIN_COVERAGE);

  const lines: string[] = [];
  lines.push(`_Generated by \`npm run story:matrix\` from ${stories.length} story file(s). Goal: every column ≥${MIN_COVERAGE}._`);
  lines.push('');
  lines.push('Theme headers: `Cf` conflict · `Fl` failure · `Dl` deadline · `Am` ambiguity · `If` influence · `Tc` technical.');
  lines.push('');
  lines.push(header);
  lines.push(sep);
  if (rows.length) lines.push(...rows);
  lines.push(totalRow);
  lines.push('');
  if (underCovered.length) {
    lines.push(`⚠️ **Under-covered (<${MIN_COVERAGE}):** ${underCovered.join(', ')}`);
  } else {
    lines.push(`✅ All ${allHeads.length} columns covered by ≥${MIN_COVERAGE} stories.`);
  }

  return { block: lines.join('\n'), underCovered };
}

function main(): void {
  if (!existsSync(README)) {
    console.error(`README not found: ${README}`);
    process.exit(1);
  }
  const readme = readFileSync(README, 'utf8');
  const si = readme.indexOf(START);
  const ei = readme.indexOf(END);
  if (si === -1 || ei === -1 || ei < si) {
    console.error(`Matrix markers missing or out of order in behavioral/README.md.`);
    console.error(`Expected "${START}" followed by "${END}". Not modifying the file.`);
    process.exit(1);
  }

  const stories = readStories();
  const { block, underCovered } = buildBlock(stories);

  const before = readme.slice(0, si + START.length);
  const after = readme.slice(ei);
  writeFileSync(README, `${before}\n${block}\n${after}`);

  console.log(`Rebuilt coverage matrix from ${stories.length} story file(s).`);
  if (underCovered.length) {
    console.log(`Under-covered columns (<${MIN_COVERAGE}): ${underCovered.join(', ')}`);
  } else {
    console.log(`All columns covered by ≥${MIN_COVERAGE} stories.`);
  }
}

main();
